
import os

# print os.getcwd()
# source_list=filter(lambda x:x[-4:]=='.cpp',os.listdir('../src'))
# env=Environment()
# env.Append(CPPPATH=['../include'])
# source_list.append('../src/cvio.cpp')
# print source_list
# env.Program(target='compvis-test',src=source_list)

#######################################################

env=Environment()

env.Append(CPPPATH = ['.','/usr/include','include',
                      '../extern/cxcore/include',
                      '../extern/cv/include',
                      '../extern/highgui/include',
                      '../include'])
debug = ARGUMENTS.get('debug', 1)
win32 = ARGUMENTS.get('win32', 0)

if int(debug):
  env.Append(CPPFLAGS = ['-g','-Wall'])
  env.Append(OBJPREFIX = '.obj_debug/')
else:
  env.Append(CPPFLAGS = ['-O2','-Wall'])
  env.Append(OBJPREFIX = '.obj_release/')

env.Append(LIBS = ['cxcore','cv','highgui','compvis'])
env.Append(LIBPATH = ['/usr/lib','../lib'])
env.Append(RPATH = ['/usr/lib','.','../lib'])

header_list=[]
env.Program(target='../bin/facetrain',source='main36_facetrain.cpp',header=header_list)
env.Program(target='../bin/facemake24',source='main36_makeface24x24.cpp',header=header_list)

env.Append(LIBS = ['avcodec','avdevice','avformat','avutil'])
env.Append(LIBPATH = ['../extern/highgui/extern/lib'])
env.Append(RPATH = ['../extern/highgui/extern/lib'])

env.Program(target='../bin/template',source='main00_template.cpp',header=header_list)
env.Program(target='../bin/pwptracker',source='main27_pwptracker.cpp',header=header_list)


