#############################################################################
# Makefile for building: compvis
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Feb 24 20:46:36 2014
# Project:  compvis.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile compvis.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-extern-cxcore \
		sub-demo

extern/cxcore//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) extern/cxcore/ || $(MKDIR) extern/cxcore/ 
	cd extern/cxcore/ && $(QMAKE) /home/liangfu/workspace/compvis/extern/cxcore/cxcore.pro -o $(MAKEFILE)
sub-extern-cxcore-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) extern/cxcore/ || $(MKDIR) extern/cxcore/ 
	cd extern/cxcore/ && $(QMAKE) /home/liangfu/workspace/compvis/extern/cxcore/cxcore.pro -o $(MAKEFILE)
sub-extern-cxcore: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE)
sub-extern-cxcore-make_default-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) 
sub-extern-cxcore-make_default: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) 
sub-extern-cxcore-make_first-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) first
sub-extern-cxcore-make_first: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) first
sub-extern-cxcore-all-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) all
sub-extern-cxcore-all: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) all
sub-extern-cxcore-clean-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) clean
sub-extern-cxcore-clean: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) clean
sub-extern-cxcore-distclean-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) distclean
sub-extern-cxcore-distclean: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) distclean
sub-extern-cxcore-install_subtargets-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) install
sub-extern-cxcore-install_subtargets: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) install
sub-extern-cxcore-uninstall_subtargets-ordered: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-extern-cxcore-uninstall_subtargets: extern/cxcore//$(MAKEFILE) FORCE
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) uninstall
demo//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) demo/ || $(MKDIR) demo/ 
	cd demo/ && $(QMAKE) /home/liangfu/workspace/compvis/demo/demo.pro -o $(MAKEFILE)
sub-demo-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) demo/ || $(MKDIR) demo/ 
	cd demo/ && $(QMAKE) /home/liangfu/workspace/compvis/demo/demo.pro -o $(MAKEFILE)
sub-demo: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE)
sub-demo-make_default-ordered: demo//$(MAKEFILE) sub-extern-cxcore-make_default-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) 
sub-demo-make_default: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) 
sub-demo-make_first-ordered: demo//$(MAKEFILE) sub-extern-cxcore-make_first-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) first
sub-demo-make_first: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) first
sub-demo-all-ordered: demo//$(MAKEFILE) sub-extern-cxcore-all-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) all
sub-demo-all: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) all
sub-demo-clean-ordered: demo//$(MAKEFILE) sub-extern-cxcore-clean-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) clean
sub-demo-clean: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) clean
sub-demo-distclean-ordered: demo//$(MAKEFILE) sub-extern-cxcore-distclean-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demo-distclean: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demo-install_subtargets-ordered: demo//$(MAKEFILE) sub-extern-cxcore-install_subtargets-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) install
sub-demo-install_subtargets: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) install
sub-demo-uninstall_subtargets-ordered: demo//$(MAKEFILE) sub-extern-cxcore-uninstall_subtargets-ordered  FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-demo-uninstall_subtargets: demo//$(MAKEFILE) FORCE
	cd demo/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: compvis.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile compvis.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile compvis.pro

qmake_all: sub-extern-cxcore-qmake_all sub-demo-qmake_all FORCE

make_default: sub-extern-cxcore-make_default-ordered sub-demo-make_default-ordered FORCE
make_first: sub-extern-cxcore-make_first-ordered sub-demo-make_first-ordered FORCE
all: sub-extern-cxcore-all-ordered sub-demo-all-ordered FORCE
clean: sub-extern-cxcore-clean-ordered sub-demo-clean-ordered FORCE
distclean: sub-extern-cxcore-distclean-ordered sub-demo-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-extern-cxcore-install_subtargets-ordered sub-demo-install_subtargets-ordered FORCE
uninstall_subtargets: sub-extern-cxcore-uninstall_subtargets-ordered sub-demo-uninstall_subtargets-ordered FORCE

sub-extern-cxcore-check_ordered: extern/cxcore/$(MAKEFILE)
	cd extern/cxcore/ && $(MAKE) -f $(MAKEFILE) check
sub-demo-check_ordered: demo/$(MAKEFILE) sub-extern-cxcore-check_ordered 
	cd demo/ && $(MAKE) -f $(MAKEFILE) check
check: sub-extern-cxcore-check_ordered sub-demo-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

