
import os

print os.getcwd()
source_list=filter(lambda x:x[-4:]=='.cpp',os.listdir(os.getcwd()))
print source_list

env=Environment()
env.ParseConfig('wx-config --cxxflags --libs')
env.Append(CXXFLAGS=['-Wall','-g'])
env.Append(RPATH='/usr/local/lib')

env.Program(target='../../bin/compvis',source=source_list)
